services:
  - type: web
    name: 4noobstracker
    runtime: ruby
    buildCommand: "./bin/render-build"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
